update fail on 0 config files

diff --git a/config-checks.template.yaml b/config-checks.template.yaml
--- a/config-checks.template.yaml
+++ b/config-checks.template.yaml
@@ -26,7 +26,11 @@
     # Report results as table
     - trivy config --ignorefile ${TRIVY_IGNOREFILE_DIR} --exit-code ${EXIT_CODE_ON_FINDINGS} --format table ${DIRECTORY}
     # Fail if 0 config files are found in folder. Such case happens when there is any error in your helm chart.
-    - (trivy config charts --ignorefile ${TRIVY_IGNOREFILE_DIR} 2>&1 >/dev/null | grep 'Detected config files: 0') && exit 1
+    - >
+      if trivy config charts --ignorefile ${TRIVY_IGNOREFILE_DIR} 2>&1 | grep -q 'Detected config files: 0'; then
+        echo "Detected 0 config files. Something is wrong. Check your helm chart or other config files for possible errors. Running trivy with --debug option should help as well."
+        exit 1
+      fi
   cache:
     paths:
       - .trivycache/
